# Generated by Django 5.0.1 on 2024-03-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirestoreHospitalUsers',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('accountType', models.CharField(blank=True, max_length=255, null=True)),
                ('bloodGroup', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('medicalField', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('nin', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('timeStamp', models.DateTimeField(blank=True, null=True)),
                ('userIssues', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
    ]
