# Generated by Django 5.0.1 on 2024-03-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAPIKeyModel',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
